workflows:
  ios-build:
    name: iOS build
    environment:
      xcode: latest
      cocoapods: default
      ruby: 3.1.0
      vars:
        GITHUB_USER: ${{github.username}}
        GITHUB_TOKEN: ${{github.token}}
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Cài đặt Bundler
        script: |
          gem install bundler
      - name: Cài đặt các phụ thuộc từ Gemfile
        script: |
          bundle install || echo "No Gemfile found, skipping bundle install"
      - name: Cài đặt CocoaPods
        script: |
          cd ios
          bundle exec pod install
      - name: Build ứng dụng iOS
        script: |
          xcodebuild -workspace ios/Uniqlo.xcodeproj -scheme Uniqlo -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/build/Uniqlo.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/Uniqlo.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath $CM_BUILD_DIR/build/Uniqlo.ipa
    artifacts:
      - $CM_BUILD_DIR/build/Uniqlo.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
