workflows:
  react_native_ios:
    name: Build React Native iOS
    environment:
      node: 16
      xcode: latest
    scripts:
      - npm install
      - cd ios && pod install
    artifacts:
      - build/ios/*.ipa
    app_store_connect:
      apple_id: "<YOUR_APPLE_ID>"
      team_id: "<YOUR_TEAM_ID>"
      api_key: Encrypted(<YOUR_API_KEY>)
    publishing:
      app_store:
        submit_to_app_store: true
