workflows:
  ios-build:
    name: iOS build
    environment:
      xcode: latest
      cocoapods: default
      vars:
        GITHUB_USER: ${{github.username}}
        GITHUB_TOKEN: ${{github.token}}
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Cài đặt Bundler
        script: |
          gem install bundler
      - name: Cài đặt dependencies
        script: |
          bundle install || echo "No Gemfile found, skipping bundle install"
          cd ios
          pod install
      - name: Build ứng dụng iOS
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/build/Runner.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/Runner.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath $CM_BUILD_DIR/build/Runner.ipa
    artifacts:
      - $CM_BUILD_DIR/build/Runner.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com