workflows:
  build_ios:
    name: Build iOS App
    environment:
      xcode: latest
      node: 16
    scripts:
      - yarn install
      - cd ios && pod install
      - xcodebuild -workspace ios/uniqlo.xcworkspace \
                    -scheme uniqlo \
                    -sdk iphoneos \
                    -configuration Release \
                    -archivePath build/uniqlo.xcarchive archive
      - xcodebuild -exportArchive \
                    -archivePath build/uniqlo.xcarchive \
                    -exportOptionsPlist ios/exportOptions.plist \
                    -exportPath build
    artifacts:
      - build/*.ipa
