workflows:
  build_ios:
    name: Build iOS App
    environment:
      xcode: latest
      node: 20.12.2
    scripts:
      - npm install
      - cd ios && pod install
      - xcodebuild -workspace ios/<YourAppName>.xcworkspace \
                    -scheme <YourAppName> \
                    -sdk iphoneos \
                    -configuration Release \
                    -archivePath build/YourAppName.xcarchive archive
      - xcodebuild -exportArchive \
                    -archivePath build/YourAppName.xcarchive \
                    -exportOptionsPlist ios/exportOptions.plist \
                    -exportPath build
    artifacts:
      - build/*.ipa
