version: 2.1

jobs:
  build:
    macos:
      xcode: "12.4.0" # Chọn phiên bản Xcode phù hợp với dự án của bạn
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            bundle install # Nếu bạn sử dụng Bundler
            pod install # Nếu bạn sử dụng CocoaPods
      - run:
          name: Build and test
          command: xcodebuild -workspace YourProject.xcworkspace -scheme YourScheme -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' clean build test
