version: 2.1

jobs:
  build:
    macos:
      xcode: "14.2.0"  # Sử dụng phiên bản Xcode 15
    resource_class: macos.medium  # Đảm bảo sử dụng tài nguyên hợp lệ
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            brew install nvm
            export NVM_DIR="$HOME/.nvm"
            [ -s "$(brew --prefix nvm)/nvm.sh" ] && \. "$(brew --prefix nvm)/nvm.sh"
            nvm install 14
            nvm use 14
      - run:
          name: Install Yarn
          command: npm install -g yarn
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Install CocoaPods
          command: |
            cd ios
            pod install
      - run:
          name: Build and test
          command: |
            cd ios
            xcodebuild -workspace YourProject.xcworkspace -scheme YourScheme -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' clean build test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
